version: '3'

volumes:
  pgdata:
  kafka-data:

networks:
  backend:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: ms_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USERNAME=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: always
    networks:
      - backend

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/bitnami/kafka
    restart: always
    networks:
      - backend

  keycloak-ms:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak-ms
    ports:
      - "8005:8080"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASS}
      - KEYCLOAK_HTTP_PORT=8080
      - KEYCLOAK_HOSTNAME=localhost
    volumes:
      - ./keycloak-themes:/opt/keycloak/themes
    command: ["start-dev"]
    networks:
      - backend