version: '3'

volumes:
  pgdata:

services:
  postgres:
    image: postgres
    container_name: ms_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pollsdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
