version: '3'

volumes:
  pgdata:
  kafka-data:

services:
  postgres:
    image: postgres
    container_name: ms_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polls_platform_bd
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: always
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/bitnami/kafka
    restart: always
  keycloak-ms:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak-ms
    ports:
      - "8005:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_HTTP_PORT=8080
      - KEYCLOAK_HOSTNAME=localhost
    volumes:
      - ./keycloak-themes:/opt/keycloak/themes

    command: ["start-dev"]
